[package]
name = "kiwi"
version = "0.20.4-1"
edition = "2021"

[dependencies]
either = "1.15"
thiserror = "2.0"
widestring = "1.2"

[dev-dependencies]
anyhow = "1.0"

[build-dependencies]
bindgen = "0.71"
